CREATE TABLE IMAGE (
    id BIGSERIAL PRIMARY KEY,
    url TEXT NOT NULL
);

CREATE TABLE QUIZ (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    image_id BIGINT DEFAULT NULL,
    expiration_date DATE NOT NULL,
    CONSTRAINT fk_quiz_image_id
    FOREIGN KEY (image_id) REFERENCES Image(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OPTION (
    id BIGSERIAL PRIMARY KEY,
    description TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    question_id BIGINT NOT NULL,
    CONSTRAINT fk_option_question_id
    FOREIGN KEY (question_id) REFERENCES Question(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE QUESTION (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    quiz_id BIGINT NOT NULL,
    image_id BIGINT DEFAULT NULL,
    CONSTRAINT fk_question_quiz_id
    FOREIGN KEY (quiz_id) REFERENCES Quiz(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_question_image_id
    FOREIGN KEY (image_id) REFERENCES Image(id) ON DELETE CASCADE ON UPDATE CASCADE
);
